#!/usr/bin/env python3
"""
VoiceFlow Installer
===================
Run this once to set up everything:

    python install.py

What it does:
  1. Checks Python version (≥ 3.9 required)
  2. Installs all dependencies
  3. Downloads the selected Whisper model
  4. Writes a starter config.yaml if none exists
  5. Creates platform launch scripts
"""

from __future__ import annotations

import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

MIN_PYTHON = (3, 9)
PLATFORM = platform.system()

BANNER = r"""
  __     __    _           _____ _
  \ \   / /__ (_) ___ ___|  ___| | _____      __
   \ \ / / _ \| |/ __/ _ \ |_  | |/ _ \ \ /\ / /
    \ V / (_) | | (_|  __/  _| | | (_) \ V  V /
     \_/ \___/|_|\___\___|_|   |_|\___/ \_/\_/

  Offline-first AI voice dictation for any app
  ─────────────────────────────────────────────
"""

MODELS = {
    "tiny":     ("tiny", "~75 MB",   "Fastest — basic accuracy"),
    "base":     ("base", "~145 MB",  "Good balance"),
    "small":    ("small","~466 MB",  "Recommended ★"),
    "medium":   ("medium","~1.5 GB", "High accuracy"),
    "large-v3": ("large-v3","~3.1 GB","Best accuracy (needs >4GB RAM)"),
}


def cprint(msg: str, color: str = "reset") -> None:
    codes = {"green": "32", "yellow": "33", "red": "31", "cyan": "36",
             "bold": "1", "reset": "0"}
    print(f"\033[{codes.get(color, '0')}m{msg}\033[0m")


def check_python() -> None:
    if sys.version_info < MIN_PYTHON:
        cprint(
            f"✗ Python {MIN_PYTHON[0]}.{MIN_PYTHON[1]}+ required "
            f"(you have {sys.version})",
            "red",
        )
        sys.exit(1)
    cprint(f"✓ Python {sys.version.split()[0]}", "green")


def install_deps() -> None:
    cprint("\n📦 Installing dependencies…", "cyan")
    cmd = [sys.executable, "-m", "pip", "install", "-r", "requirements.txt", "-q"]
    try:
        subprocess.check_call(cmd)
        cprint("✓ Dependencies installed", "green")
    except subprocess.CalledProcessError:
        cprint("⚠ Some packages failed — check output above", "yellow")
        cprint("  Continuing anyway…", "yellow")


def pick_model() -> str:
    cprint("\n🤖 Choose Whisper model for local ASR:", "cyan")
    keys = list(MODELS.keys())
    for i, key in enumerate(keys, 1):
        _, size, desc = MODELS[key]
        star = " ◄ default" if key == "small" else ""
        print(f"  [{i}] {key:12s} {size:8s}  {desc}{star}")

    while True:
        raw = input("\n  Enter number [3]: ").strip()
        if not raw:
            return "small"
        try:
            idx = int(raw) - 1
            if 0 <= idx < len(keys):
                return keys[idx]
        except ValueError:
            pass
        cprint("  Invalid choice — try again", "yellow")


def download_model(model_name: str) -> None:
    cprint(f"\n⬇  Downloading faster-whisper model: {model_name}…", "cyan")
    cprint("   (This may take a few minutes on first run)", "yellow")
    try:
        # faster-whisper auto-downloads to ~/.cache/huggingface on first use
        # We trigger it now so the user doesn't wait during dictation
        script = (
            "from faster_whisper import WhisperModel; "
            f"WhisperModel('{model_name}', device='cpu', compute_type='int8')"
        )
        subprocess.check_call([sys.executable, "-c", script])
        cprint(f"✓ Model '{model_name}' ready", "green")
    except Exception as exc:
        cprint(f"⚠ Model download failed: {exc}", "yellow")
        cprint("  It will download automatically on first dictation.", "yellow")


def write_config(model_name: str) -> None:
    cfg_path = Path("config.yaml")
    if cfg_path.exists():
        cprint(f"\n✓ config.yaml already exists — skipping", "green")
        return

    # Read the template and patch the model name
    template_path = Path("config.yaml")
    # We'll just write a minimal config pointing to the chosen model
    config_content = f"""# VoiceFlow configuration — generated by install.py
# Edit any value and restart VoiceFlow.

asr:
  backend: local
  local:
    model: {model_name}
    compute_type: auto
    device: auto
  nim:
    api_key: ""
    endpoint: "https://integrate.api.nvidia.com/v1"
    model: "nvidia/parakeet-tdt-1.1b"
    timeout: 10

hotkeys:
  toggle: "<alt>+<space>"
  push_to_talk: "<alt>+<shift>+<space>"
  switch_backend: "<ctrl>+<alt>+b"
  quit: "<ctrl>+<alt>+q"

injection:
  method: clipboard
  restore_clipboard: true
  paste_delay: 0.05

polish:
  enabled: false
  backend: ollama
  ollama:
    endpoint: "http://localhost:11434"
    model: "llama3.2"
  openrouter:
    api_key: ""
    model: "qwen/qwen-2.5-7b-instruct:free"
  nim:
    api_key: ""
    model: "meta/llama-3.1-8b-instruct"

ui:
  orb:
    size: 64
    position: bottom-right
    margin: 24
    opacity: 0.95

audio:
  sample_rate: 16000
  channels: 1
  chunk_ms: 30
  vad_aggressiveness: 2
  silence_duration: 0.6
  max_recording: 30
"""
    cfg_path.write_text(config_content)
    cprint(f"✓ config.yaml written", "green")


def create_launchers() -> None:
    cprint("\n🚀 Creating launch scripts…", "cyan")

    if PLATFORM == "Windows":
        bat = Path("VoiceFlow.bat")
        bat.write_text(
            f'@echo off\n"{sys.executable}" main.py %*\n',
            encoding="utf-8",
        )
        cprint(f"✓ VoiceFlow.bat created — double-click to start", "green")

        # Also create a VBS launcher (no console window)
        vbs = Path("VoiceFlow_silent.vbs")
        vbs.write_text(
            f'CreateObject("WScript.Shell").Run '
            f'"""{sys.executable}"" main.py", 0, False\n',
            encoding="utf-8",
        )
        cprint(f"✓ VoiceFlow_silent.vbs — no console window", "green")

    else:
        sh = Path("voiceflow.sh")
        sh.write_text(
            f"#!/bin/bash\n{sys.executable} main.py \"$@\"\n"
        )
        sh.chmod(0o755)
        cprint(f"✓ voiceflow.sh created — run: ./voiceflow.sh", "green")


def print_next_steps(model: str) -> None:
    cprint("\n" + "─" * 50, "bold")
    cprint("  ✅  VoiceFlow is ready!", "green")
    cprint("─" * 50, "bold")
    print(f"""
  Model:    {model}
  Hotkey:   Alt + Space  (toggle dictation)
            Alt+Shift+Space  (hold to talk)

  Start:""")

    if PLATFORM == "Windows":
        print("    Double-click  VoiceFlow.bat")
        print("    or:  python main.py")
    else:
        print("    ./voiceflow.sh")
        print("    or:  python main.py")

    print("""
  Options:
    python main.py --backend nim    # use NVIDIA NIM
    python main.py --model large-v3 # override model
    python main.py --debug          # verbose logging

  Edit config.yaml to change any setting.

  Hotkeys:
    Alt+Space          toggle dictation
    Alt+Shift+Space    push-to-talk
    Ctrl+Alt+B         switch backend
    Ctrl+Alt+Q         quit

  Enjoy hands-free typing! ✨
""")


def main() -> None:
    print(BANNER)

    check_python()

    install_deps()

    model = pick_model()

    download_model(model)

    write_config(model)

    create_launchers()

    print_next_steps(model)


if __name__ == "__main__":
    main()
